# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redditDataExtractorGUI.ui'
#
# Created: Sun Jul 27 02:00:51 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RddtDataExtractorMainWindow(object):
    def setupUi(self, RddtDataExtractorMainWindow):
        RddtDataExtractorMainWindow.setObjectName(_fromUtf8("RddtDataExtractorMainWindow"))
        RddtDataExtractorMainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(RddtDataExtractorMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.subredditList = QtGui.QListView(self.centralwidget)
        self.subredditList.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.subredditList.setObjectName(_fromUtf8("subredditList"))
        self.gridLayout.addWidget(self.subredditList, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.userLabel = QtGui.QLabel(self.centralwidget)
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.horizontalLayout_4.addWidget(self.userLabel)
        self.userListChooser = QtGui.QComboBox(self.centralwidget)
        self.userListChooser.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.userListChooser.setAcceptDrops(False)
        self.userListChooser.setEditable(False)
        self.userListChooser.setObjectName(_fromUtf8("userListChooser"))
        self.horizontalLayout_4.addWidget(self.userListChooser)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.subredditLabel = QtGui.QLabel(self.centralwidget)
        self.subredditLabel.setObjectName(_fromUtf8("subredditLabel"))
        self.horizontalLayout_3.addWidget(self.subredditLabel)
        self.subredditListChooser = QtGui.QComboBox(self.centralwidget)
        self.subredditListChooser.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.subredditListChooser.setObjectName(_fromUtf8("subredditListChooser"))
        self.horizontalLayout_3.addWidget(self.subredditListChooser)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.userList = QtGui.QListView(self.centralwidget)
        self.userList.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.userList.setObjectName(_fromUtf8("userList"))
        self.gridLayout.addWidget(self.userList, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addUserBtn = QtGui.QToolButton(self.centralwidget)
        self.addUserBtn.setObjectName(_fromUtf8("addUserBtn"))
        self.horizontalLayout.addWidget(self.addUserBtn)
        self.deleteUserBtn = QtGui.QToolButton(self.centralwidget)
        self.deleteUserBtn.setObjectName(_fromUtf8("deleteUserBtn"))
        self.horizontalLayout.addWidget(self.deleteUserBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.directoryBox = QtGui.QLineEdit(self.centralwidget)
        self.directoryBox.setObjectName(_fromUtf8("directoryBox"))
        self.gridLayout.addWidget(self.directoryBox, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.userSubBtn = QtGui.QRadioButton(self.centralwidget)
        self.userSubBtn.setChecked(True)
        self.userSubBtn.setObjectName(_fromUtf8("userSubBtn"))
        self.horizontalLayout_5.addWidget(self.userSubBtn)
        self.allUserBtn = QtGui.QRadioButton(self.centralwidget)
        self.allUserBtn.setChecked(False)
        self.allUserBtn.setObjectName(_fromUtf8("allUserBtn"))
        self.horizontalLayout_5.addWidget(self.allUserBtn)
        self.allSubBtn = QtGui.QRadioButton(self.centralwidget)
        self.allSubBtn.setObjectName(_fromUtf8("allSubBtn"))
        self.horizontalLayout_5.addWidget(self.allSubBtn)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 2)
        self.downloadBtn = QtGui.QPushButton(self.centralwidget)
        self.downloadBtn.setObjectName(_fromUtf8("downloadBtn"))
        self.gridLayout.addWidget(self.downloadBtn, 6, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.addSubredditBtn = QtGui.QToolButton(self.centralwidget)
        self.addSubredditBtn.setObjectName(_fromUtf8("addSubredditBtn"))
        self.horizontalLayout_2.addWidget(self.addSubredditBtn)
        self.deleteSubredditBtn = QtGui.QToolButton(self.centralwidget)
        self.deleteSubredditBtn.setObjectName(_fromUtf8("deleteSubredditBtn"))
        self.horizontalLayout_2.addWidget(self.deleteSubredditBtn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.logTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logTextEdit.setObjectName(_fromUtf8("logTextEdit"))
        self.gridLayout.addWidget(self.logTextEdit, 7, 0, 1, 2)
        self.directorySelectBtn = QtGui.QPushButton(self.centralwidget)
        self.directorySelectBtn.setObjectName(_fromUtf8("directorySelectBtn"))
        self.gridLayout.addWidget(self.directorySelectBtn, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        RddtDataExtractorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RddtDataExtractorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuType = QtGui.QMenu(self.menubar)
        self.menuType.setObjectName(_fromUtf8("menuType"))
        self.menuNew = QtGui.QMenu(self.menuType)
        self.menuNew.setObjectName(_fromUtf8("menuNew"))
        self.menuRemove = QtGui.QMenu(self.menuType)
        self.menuRemove.setObjectName(_fromUtf8("menuRemove"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        RddtDataExtractorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RddtDataExtractorMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RddtDataExtractorMainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionCreate_New_Subreddit_List = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionCreate_New_Subreddit_List.setObjectName(_fromUtf8("actionCreate_New_Subreddit_List"))
        self.actionSubreddit_List = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionSubreddit_List.setObjectName(_fromUtf8("actionSubreddit_List"))
        self.actionUser_List = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionUser_List.setObjectName(_fromUtf8("actionUser_List"))
        self.actionSettings_2 = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionSettings_2.setObjectName(_fromUtf8("actionSettings_2"))
        self.actionSave = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionDownloaded_Reddit_User_Posts = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionDownloaded_Reddit_User_Posts.setWhatsThis(_fromUtf8(""))
        self.actionDownloaded_Reddit_User_Posts.setObjectName(_fromUtf8("actionDownloaded_Reddit_User_Posts"))
        self.actionRemove_Subreddit_List = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionRemove_Subreddit_List.setObjectName(_fromUtf8("actionRemove_Subreddit_List"))
        self.actionRemove_User_List = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionRemove_User_List.setObjectName(_fromUtf8("actionRemove_User_List"))
        self.actionDownloaded_Subreddit_Posts = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionDownloaded_Subreddit_Posts.setObjectName(_fromUtf8("actionDownloaded_Subreddit_Posts"))
        self.actionAdd = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionNew_Subreddit = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionNew_Subreddit.setObjectName(_fromUtf8("actionNew_Subreddit"))
        self.actionNew_User = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionNew_User.setObjectName(_fromUtf8("actionNew_User"))
        self.actionRemove_Selected_Subreddit = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionRemove_Selected_Subreddit.setObjectName(_fromUtf8("actionRemove_Selected_Subreddit"))
        self.actionRemove_Selected_User = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionRemove_Selected_User.setObjectName(_fromUtf8("actionRemove_Selected_User"))
        self.actionAbout = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionRemaining_Imgur_Requests = QtGui.QAction(RddtDataExtractorMainWindow)
        self.actionRemaining_Imgur_Requests.setObjectName(_fromUtf8("actionRemaining_Imgur_Requests"))
        self.menuNew.addAction(self.actionUser_List)
        self.menuNew.addAction(self.actionNew_User)
        self.menuNew.addAction(self.actionSubreddit_List)
        self.menuNew.addAction(self.actionNew_Subreddit)
        self.menuRemove.addAction(self.actionRemove_User_List)
        self.menuRemove.addAction(self.actionRemove_Selected_User)
        self.menuRemove.addAction(self.actionRemove_Subreddit_List)
        self.menuRemove.addAction(self.actionRemove_Selected_Subreddit)
        self.menuType.addAction(self.menuNew.menuAction())
        self.menuType.addAction(self.menuRemove.menuAction())
        self.menuType.addAction(self.actionSave)
        self.menuType.addAction(self.actionSettings_2)
        self.menuType.addSeparator()
        self.menuType.addAction(self.actionExit)
        self.menuView.addAction(self.actionDownloaded_Reddit_User_Posts)
        self.menuView.addAction(self.actionDownloaded_Subreddit_Posts)
        self.menuView.addAction(self.actionRemaining_Imgur_Requests)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuType.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(RddtDataExtractorMainWindow)
        QtCore.QMetaObject.connectSlotsByName(RddtDataExtractorMainWindow)

    def retranslateUi(self, RddtDataExtractorMainWindow):
        RddtDataExtractorMainWindow.setWindowTitle(_translate("RddtDataExtractorMainWindow", "Data Extractor for reddit", None))
        self.userLabel.setToolTip(_translate("RddtDataExtractorMainWindow", "Reddit usernames to download content from.", None))
        self.userLabel.setText(_translate("RddtDataExtractorMainWindow", "Users to Download From", None))
        self.userListChooser.setToolTip(_translate("RddtDataExtractorMainWindow", "<html><head/><body><p>Lists of Users you can download from. </p><p>If you want to download from separate users / subreddits, make a new list.</p></body></html>", None))
        self.subredditLabel.setToolTip(_translate("RddtDataExtractorMainWindow", "Subreddits to download content from.", None))
        self.subredditLabel.setText(_translate("RddtDataExtractorMainWindow", "Subreddits To Download From", None))
        self.subredditListChooser.setToolTip(_translate("RddtDataExtractorMainWindow", "<html><head/><body><p>Lists of Subreddits you can download from. </p><p>If you want to download from separate users / subreddits, make a new list.</p></body></html>", None))
        self.addUserBtn.setToolTip(_translate("RddtDataExtractorMainWindow", "Add a user.", None))
        self.addUserBtn.setText(_translate("RddtDataExtractorMainWindow", "+", None))
        self.deleteUserBtn.setToolTip(_translate("RddtDataExtractorMainWindow", "Remove selected user.", None))
        self.deleteUserBtn.setText(_translate("RddtDataExtractorMainWindow", "-", None))
        self.directoryBox.setToolTip(_translate("RddtDataExtractorMainWindow", "Directory to download content to.", None))
        self.userSubBtn.setToolTip(_translate("RddtDataExtractorMainWindow", "Download content from the users in the users list only if they have posted in the subreddits in the subreddit list.", None))
        self.userSubBtn.setText(_translate("RddtDataExtractorMainWindow", "Constrain Selected Users To Selected Subreddits", None))
        self.allUserBtn.setToolTip(_translate("RddtDataExtractorMainWindow", "Download content from users in the users list, from any subreddit.", None))
        self.allUserBtn.setText(_translate("RddtDataExtractorMainWindow", "Selected Users\' Content in All Subreddits", None))
        self.allSubBtn.setToolTip(_translate("RddtDataExtractorMainWindow", "Download content from the subreddits in the subreddits list.", None))
        self.allSubBtn.setText(_translate("RddtDataExtractorMainWindow", "Selected Subreddits\' Content", None))
        self.downloadBtn.setToolTip(_translate("RddtDataExtractorMainWindow", "Begin to download content.", None))
        self.downloadBtn.setText(_translate("RddtDataExtractorMainWindow", "Download!", None))
        self.addSubredditBtn.setToolTip(_translate("RddtDataExtractorMainWindow", "Add a subreddit.", None))
        self.addSubredditBtn.setText(_translate("RddtDataExtractorMainWindow", "+", None))
        self.deleteSubredditBtn.setToolTip(_translate("RddtDataExtractorMainWindow", "Remove selected subreddit.", None))
        self.deleteSubredditBtn.setText(_translate("RddtDataExtractorMainWindow", "-", None))
        self.logTextEdit.setToolTip(_translate("RddtDataExtractorMainWindow", "Status of the download is displayed here.", None))
        self.directorySelectBtn.setToolTip(_translate("RddtDataExtractorMainWindow", "Select where downloaded content will be saved to.", None))
        self.directorySelectBtn.setText(_translate("RddtDataExtractorMainWindow", "Set directory to save to", None))
        self.menuType.setTitle(_translate("RddtDataExtractorMainWindow", "&File", None))
        self.menuNew.setTitle(_translate("RddtDataExtractorMainWindow", "&New", None))
        self.menuRemove.setTitle(_translate("RddtDataExtractorMainWindow", "&Remove", None))
        self.menuView.setTitle(_translate("RddtDataExtractorMainWindow", "&View", None))
        self.menuHelp.setTitle(_translate("RddtDataExtractorMainWindow", "Help", None))
        self.actionExit.setText(_translate("RddtDataExtractorMainWindow", "E&xit", None))
        self.actionCreate_New_Subreddit_List.setText(_translate("RddtDataExtractorMainWindow", "Create New Subreddit List", None))
        self.actionSubreddit_List.setText(_translate("RddtDataExtractorMainWindow", "New &Subreddit List", None))
        self.actionSubreddit_List.setShortcut(_translate("RddtDataExtractorMainWindow", "Ctrl+2", None))
        self.actionUser_List.setText(_translate("RddtDataExtractorMainWindow", "New &User List", None))
        self.actionUser_List.setShortcut(_translate("RddtDataExtractorMainWindow", "Ctrl+1", None))
        self.actionSettings_2.setText(_translate("RddtDataExtractorMainWindow", "&Settings", None))
        self.actionSave.setText(_translate("RddtDataExtractorMainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("RddtDataExtractorMainWindow", "Ctrl+S", None))
        self.actionDownloaded_Reddit_User_Posts.setText(_translate("RddtDataExtractorMainWindow", "&Downloaded Reddit User Posts", None))
        self.actionRemove_Subreddit_List.setText(_translate("RddtDataExtractorMainWindow", "Remove Selected &Subreddit List", None))
        self.actionRemove_Subreddit_List.setShortcut(_translate("RddtDataExtractorMainWindow", "Ctrl+4", None))
        self.actionRemove_User_List.setText(_translate("RddtDataExtractorMainWindow", "Remove Selected &User List", None))
        self.actionRemove_User_List.setShortcut(_translate("RddtDataExtractorMainWindow", "Ctrl+3", None))
        self.actionDownloaded_Subreddit_Posts.setText(_translate("RddtDataExtractorMainWindow", "Downloaded Subreddit Posts", None))
        self.actionAdd.setText(_translate("RddtDataExtractorMainWindow", "Add", None))
        self.actionNew_Subreddit.setText(_translate("RddtDataExtractorMainWindow", "New Subreddit", None))
        self.actionNew_Subreddit.setShortcut(_translate("RddtDataExtractorMainWindow", "Ctrl+Shift+S", None))
        self.actionNew_User.setText(_translate("RddtDataExtractorMainWindow", "New User", None))
        self.actionNew_User.setShortcut(_translate("RddtDataExtractorMainWindow", "Ctrl+Shift+U", None))
        self.actionRemove_Selected_Subreddit.setText(_translate("RddtDataExtractorMainWindow", "Remove Selected Subreddit", None))
        self.actionRemove_Selected_Subreddit.setShortcut(_translate("RddtDataExtractorMainWindow", "Ctrl+Alt+S", None))
        self.actionRemove_Selected_User.setText(_translate("RddtDataExtractorMainWindow", "Remove Selected User", None))
        self.actionRemove_Selected_User.setShortcut(_translate("RddtDataExtractorMainWindow", "Ctrl+Alt+U", None))
        self.actionAbout.setText(_translate("RddtDataExtractorMainWindow", "About", None))
        self.actionRemaining_Imgur_Requests.setText(_translate("RddtDataExtractorMainWindow", "&Remaining Imgur Requests", None))

